#!/bin/bash
export CFLAGS="-Wimplicit -Wreturn-type -Wuninitialized -g -O2"
rm -f config.h configure Makefile config.cache
rm -rf .deps
autoheader
rm -f autoh*
aclocal
automake
autoconf
./configure
make dist
make clean
make
