#ifndef JOS_MACHINE_TRAPCODES_H
#define JOS_MACHINE_TRAPCODES_H

#define T_DIVIDE	0		// divide error
#define T_DEBUG		1		// debug exception
#define T_NMI		2		// non-maskable interrupt
#define T_BRKPT		3		// breakpoint
#define T_OFLOW		4		// overflow
#define T_BOUND		5		// bounds check
#define T_ILLOP		6		// illegal opcode
#define T_DEVICE	7		// device not available 
#define T_DBLFLT	8		// double fault
/* #define T_COPROC	9 */		// reserved (not generated by recent processors)
#define T_TSS		10		// invalid task switch segment
#define T_SEGNP		11		// segment not present
#define T_STACK		12		// stack exception
#define T_GPFLT		13		// genernal protection fault
#define T_PGFLT		14		// page fault
/* #define T_RES	15 */		// reserved
#define T_FPERR		16		// floating point error
#define T_ALIGN		17		// aligment check
#define T_MCHK		18		// machine check
#define T_SIMDERR	19		// SIMD floating point error

#define T_PIC		32		/* external i8259 interrupts */
#define IRQ_CLOCK	0
#define IRQ_KBD		1
#define IRQ_UART1	3
#define IRQ_UART0	4
#define IRQ_PCMCIA	5
#define IRQ_FLOPPY	6
#define IRQ_LPT		7
#define IRQ_IRQ7	7
#define IRQ_AUX		12		// PS/2 port
#define IRQ_IRQ13	13		// coprocessor on 386
#define IRQ_ATA0	14
#define IRQ_ATA1	15
#define MAX_IRQ_PIC	15

#define T_LAPIC		(T_PIC+16)	// local APIC interrupts
#define IRQ_LINT0	16		// LINT[01] must be offsets 0 and 1
#define IRQ_LINT1	17
#define IRQ_TIMER	18
#define IRQ_ERROR	19
#define IRQ_PCINT	20
#define IRQ_SPURIOUS	31		// must have bits [3-0] == 0x0F
#define MAX_IRQ_LAPIC	31
#define NIRQS		32

#define T_SYSCALL	64

#define T_APIC		65		// external APIC interrupts
#define MAX_T_APIC	255

#define NTRAPS		256

#endif
