#ifndef JOS_MACHINE_TRAPCODES_H
#define JOS_MACHINE_TRAPCODES_H

#define SYSCALL_TRAP	48

#ifndef __ASSEMBLER__

typedef enum {
    T_DIVIDE		= 0,		/* divide error */
    T_DEBUG		= 1,		/* debug exception */
    T_NMI		= 2,		/* non-maskable interrupt */
    T_BRKPT		= 3,		/* breakpoint */
    T_OFLOW		= 4,		/* overflow */
    T_BOUND		= 5,		/* bounds check */
    T_ILLOP		= 6,		/* illegal opcode */
    T_DEVICE		= 7,		/* device not available */
    T_DBLFLT		= 8,		/* double fault */
    /* 9 reserved (not generated by recent processors) */
    T_TSS		= 10,		/* invalid task switch segment */
    T_SEGNP		= 11,		/* segment not present */
    T_STACK		= 12,		/* stack exception */
    T_GPFLT		= 13,		/* genernal protection fault */
    T_PGFLT		= 14,		/* page fault */
    /* 15 reserved */
    T_FPERR		= 16,		/* floating point error */
    T_ALIGN		= 17,		/* aligment check */
    T_MCHK		= 18,		/* machine check */
    T_SIMDERR		= 19,		/* SIMD floating point error */
    T_PIC		= 32,
    T_PIC_MAX		= 47,
    T_SYSCALL		= SYSCALL_TRAP,
    T_USERDEV		= 64,
    T_USERDEV_MAX	= 191,
    T_KERNDEV		= 192,
    T_KERNDEV_MAX	= 239,
    T_LAPIC		= 240,
    T_LAPIC_MAX		= 255,
    MAX_TRAP		= 255,
} trapno_t;

typedef enum {
    IRQ_CLOCK		= 0,
    IRQ_KBD		= 1,
    IRQ_UART1		= 3,
    IRQ_UART0		= 4,
    IRQ_PCMCIA		= 5,
    IRQ_FLOPPY		= 6,
    IRQ_LPT		= 7,
    IRQ_IRQ7		= 7,
    IRQ_AUX		= 12,		/* PS/2 port */
    IRQ_IRQ13		= 13,		/* coprocessor on 386 */
    IRQ_ATA0		= 14,
    IRQ_ATA1		= 15,
    MAX_IRQ_PIC		= 15,
    IRQ_LINT0		= 16,		/* LINT[01] must be offsets 0 and 1 */
    IRQ_LINT1		= 17,
    IRQ_TIMER		= 18,
    IRQ_ERROR		= 19,
    IRQ_PCINT		= 20,
    IRQ_SPURIOUS	= 31,		/* must have bits [3-0] == 0x0F */
    MAX_IRQ_LAPIC	= 31,
    MAX_IRQ		= 31,
} irqno_t;

#define PIC_TRAPNO(irq) ((irq) + T_PIC)
#define PIC_IRQNO(trapno) ((trapno) - T_PIC)

#define APIC_TRAPNO(irq) (((irq) - IRQ_LINT0) + T_LAPIC)
#define APIC_IRQNO(trapno) (((trapno) - T_LAPIC) + IRQ_LINT0)

#endif
#endif
