#ifndef JOS_MACHINE_SPARC_CONFIG_H
#define JOS_MACHINE_SPARC_CONFIG_H

/* Max number of MMU contexts*/
#define CTX_NCTX	256

/* Number of register windows */
#define NWINDOWS	8

/*
 * Clock frequency in kHz.
 * Based on CONFIG_CLK_MUL, CONFIG_CLK_DIV, in the chip's config.h,
 * starting from BOARD_FREQ (leon3mp.vhd), generated by Xilinx DCM.
 */
#define CLOCK_FREQ_KHZ	65000

#endif
